name: TeleportSuite
main: net.krinsoft.teleportsuite.TeleportSuite
version: ${project.version}
author: krinsdeath

commands:
  teleport:
    aliases:
      - tps
      - tp
      - tphere
      - tpa
      - tpahere
      - tpo
      - tpohere
      - tploc
      - tpcoords
      - tpaccept
      - tpreject
      - tprequests
      - tptoggle
      - tpback
      - back
      - tpworld
    usage: /<command>
permissions:
  teleport.users:
    description: Convenience node for normal users.
    default: true
    children:
      teleport.tpa: true
      teleport.tpahere: true
      teleport.requests: true
      teleport.cancel: true
      teleport.accept: true
      teleport.reject: true
      teleport.toggle: true
      teleport.back: true
      teleport.coords: true
      teleport.world.*: true
  teleport.mods:
    description: Convenience nodes for ops.
    default: op
    children:
      teleport.tp: true
      teleport.tphere: true
      teleport.tploc: true
      teleport.tpworld: true
  teleport.admins:
    description: Convenience node for overrides.
    default: false
    children:
      teleport.tpo: true
      teleport.tpohere: true