name: TeleportSuite
main: net.krinsoft.teleportsuite.TeleportSuite
version: ${project.version}
author: krinsdeath
load: startup

commands:
  teleport:
    aliases:
      - tps
      - tploc
      - tpcoords
      - tpaccept
      - tpacc
      - tpreject
      - tprej
      - tprequests
      - tpr
      - tptoggle
      - tpt
      - tpback
      - tpworld
      - tpcancel
    usage: /<command>
  tp:
    description: Allows users to teleport to each other.
    usage: /<command>
  tphere:
    description: Allows users to teleport other users to them.
    usage: /<command>
  tpa:
    description: Allows users to request teleports to each other.
    usage: /<command>
  tpahere:
    description: Allows users to request another user to teleport to them.
    usage: /<command>
  tpo:
    description: Overrides a user's teleport toggle status and teleports the sender immediately.
    usage: /<command>
  tpohere:
    description: Overrides a user's teleport toggle status and teleports them immediately to the sender.
    usage: /<command>
  back:
    description: Teleports the user to their previous location.
    usage: /<command>
permissions:
  teleport.users:
    description: Convenience node for normal users.
    default: true
    children:
      teleport.tpa: true
      teleport.tpahere: true
      teleport.requests: true
      teleport.cancel: true
      teleport.accept: true
      teleport.reject: true
      teleport.toggle: true
      teleport.back: true
      teleport.coords: true
      teleport.world.*: true
  teleport.mods:
    description: Convenience nodes for ops.
    default: op
    children:
      teleport.tp: true
      teleport.tphere: true
      teleport.tploc: true
      teleport.tpworld: true
  teleport.admins:
    description: Convenience node for overrides.
    default: false
    children:
      teleport.tpo: true
      teleport.tpohere: true